[package]
name = "airpodsd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
airpods-audio = { path = "../airpods-audio" }
airpods-core = { path = "../airpods-core" }
airpods-ipc = { path = "../airpods-ipc" }
anyhow.workspace = true
bluer.workspace = true
dirs = "6"
serde.workspace = true
tokio = { workspace = true, features = ["fs", "io-util", "process"] }
toml.workspace = true
zbus.workspace = true
zvariant.workspace = true
